// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf1ntCvH-H7LCNoPBtoOZKuxdJ_PD0Btk',
    appId: '1:235986066777:web:89c09526b475da60240048',
    messagingSenderId: '235986066777',
    projectId: 'resq-mob',
    authDomain: 'resq-mob.firebaseapp.com',
    storageBucket: 'resq-mob.firebasestorage.app',
    measurementId: 'G-YS7SM1QPJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpsSTqSS_0SvOcZYLWxLjDnq3UGwEgWq0',
    appId: '1:235986066777:android:768177a6effdcd5f240048',
    messagingSenderId: '235986066777',
    projectId: 'resq-mob',
    storageBucket: 'resq-mob.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf1ntCvH-H7LCNoPBtoOZKuxdJ_PD0Btk',
    appId: '1:235986066777:web:01d0fad2962fff34240048',
    messagingSenderId: '235986066777',
    projectId: 'resq-mob',
    authDomain: 'resq-mob.firebaseapp.com',
    storageBucket: 'resq-mob.firebasestorage.app',
    measurementId: 'G-NLPY8HSY37',
  );
}
